### ISSUE TITLE
Can't run it...

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [marcosschroh/faust-docker-compose-example#17]
`> make run-dev`

Log: 
...
faust-project_1    | DNS fwd/rev mismatch: schema-registry != schema-registry.faust-docker-compose-example_default
faust-project_1    | schema-registry [172.23.0.4] 8081 (tproxy) open
faust-project_1    | Schema Registry is up - executing command
faust-project_1    | Executing command ./run.sh
faust-project_1    | + export SIMPLE_SETTINGS=settings
faust-project_1    | + example worker --web-port=6066
faust-project_1    | Traceback (most recent call last):
faust-project_1    |   File "/usr/local/bin/example", line 10, in <module>
faust-project_1    |     from importlib.metadata import distribution
faust-project_1    | ModuleNotFoundError: No module named 'importlib.metadata'
faust-project_1    | 
faust-project_1    | During handling of the above exception, another exception occurred:
faust-project_1    | 
faust-project_1    | Traceback (most recent call last):
faust-project_1    |   File "/usr/local/bin/example", line 13, in <module>
faust-project_1    |     from importlib_metadata import distribution
faust-project_1    | ModuleNotFoundError: No module named 'importlib_metadata'
faust-project_1    | 
faust-project_1    | During handling of the above exception, another exception occurred:
faust-project_1    | 
faust-project_1    | Traceback (most recent call last):
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
faust-project_1    |     ws.require(__requires__)
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
faust-project_1    |     needed = self.resolve(parse_requirements(requirements))
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
faust-project_1    |     raise VersionConflict(dist, req).with_context(dependent_req)
faust-project_1    | pkg_resources.ContextualVersionConflict: (fastavro 0.22.3 (/usr/local/lib/python3.7/site-packages), Requirement.parse('fastavro<0.25,>=0.24'), {'python-schema-registry-client'})
faust-project_1    | 
faust-project_1    | During handling of the above exception, another exception occurred:
faust-project_1    | 
faust-project_1    | Traceback (most recent call last):
faust-project_1    |   File "/usr/local/bin/example", line 15, in <module>
faust-project_1    |     from pkg_resources import load_entry_point
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
faust-project_1    |     @_call_aside
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
faust-project_1    |     f(*args, **kwargs)
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
faust-project_1    |     working_set = WorkingSet._build_master()
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
faust-project_1    |     return cls._build_from_requirements(__requires__)
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
faust-project_1    |     dists = ws.resolve(reqs, Environment())
faust-project_1    |   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
faust-project_1    |     raise VersionConflict(dist, req).with_context(dependent_req)
faust-project_1    | pkg_resources.ContextualVersionConflict: (fastavro 0.22.3 (/usr/local/lib/python3.7/site-packages), Requirement.parse('fastavro<0.25,>=0.24'), {'python-schema-registry-client'})
faust-docker-compose-example_faust-project_1 exited with code 1

**Comment by marcosschroh** [comment]
Hi @Vasiliy-Bondarenko 

Thanks for let me know. I will fix it

**Comment by marcosschroh** [comment]
fixed by https://github.com/marcosschroh/faust-docker-compose-example/pull/18
